/**
 * A curated list of short, common, easy to type words used for
 * passphrase generation. 
 */
export const WORDLIST: readonly string[] = [
  "acorn", "action", "afraid", "airport", "almond", "amber", "anchor", "animal",
  "ankle", "answer", "apple", "arcade", "arrow", "artist", "attend", "autumn",
  "avenue", "badge", "bakery", "balloon", "bamboo", "banana", "basket", "beacon",
  "beaver", "before", "begin", "bench", "berry", "bicycle", "bird", "biscuit",
  "blanket", "blossom", "blue", "boat", "border", "bottle", "boulder", "bracket",
  "branch", "brave", "bread", "breeze", "bridge", "bright", "bronze", "brush",
  "bubble", "bucket", "budget", "bundle", "burrow", "cabin", "cable", "cactus",
  "camera", "campus", "canary", "candle", "canoe", "canvas", "canyon", "carbon",
  "carpet", "carrot", "castle", "cedar", "cellar", "chalk", "chapter", "charm",
  "cheese", "cherry", "chess", "chimney", "circle", "cloud", "clover", "coast",
  "cobalt", "coffee", "column", "comet", "compass", "coral", "corner", "cotton",
  "cousin", "coyote", "crater", "cream", "creek", "cricket", "crown", "crystal",
  "cuddle", "cursor", "custom", "dawn", "delta", "desert", "design", "diamond",
  "dinner", "dolphin", "donkey", "dragon", "drizzle", "eagle", "echo", "elbow",
  "ember", "emerald", "engine", "equal", "escape", "evening", "expand", "fabric",
  "falcon", "feather", "fence", "ferry", "field", "finger", "flame", "flannel",
  "flavor", "flower", "flute", "forest", "fossil", "fountain", "fox", "friday",
  "frost", "garden", "garlic", "gecko", "gentle", "giraffe", "glacier", "glider",
  "globe", "golden", "gopher", "granite", "grape", "gravel", "guitar", "gully",
  "hamlet", "harbor", "harvest", "hazel", "helmet", "heron", "hidden", "hollow",
  "honest", "honey", "horizon", "hunter", "iguana", "island", "ivory", "jacket",
  "jasmine", "jelly", "journal", "journey", "jungle", "kettle", "kitten", "knight",
  "ladder", "lagoon", "lantern", "laptop", "laurel", "lemon", "lentil", "letter",
  "linen", "lizard", "lobby", "locket", "lumber", "lunar", "magnet", "maple",
  "marble", "marina", "marker", "meadow", "melody", "mentor", "meteor", "mirror",
  "mitten", "modest", "monkey", "moss", "motive", "mountain", "muffin", "mustang",
  "napkin", "nectar", "needle", "noble", "notch", "number", "nutmeg", "oasis",
  "ocean", "olive", "onion", "opal", "orange", "orbit", "orchard", "otter",
  "oyster", "paddle", "palace", "panther", "papaya", "parcel", "parrot", "pebble",
  "pecan", "pelican", "penny", "pepper", "pigeon", "pillow", "pilot", "pine",
  "planet", "plaza", "pocket", "poplar", "poppy", "potato", "prairie", "puzzle",
  "quail", "quartz", "quiet", "rabbit", "raccoon", "radish", "rainbow", "raven",
  "reef", "ribbon", "ridge", "ripple", "river", "rocket", "rooster", "rustic",
  "saddle", "saffron", "salmon", "sandal", "sapling", "scarf", "school", "scooter",
  "sesame", "shadow", "shark", "shelter", "shore", "shovel", "sierra", "silver",
  "sketch", "skyline", "sleepy", "sliver", "smooth", "snail", "solar", "sparrow",
  "spiral", "spring", "spruce", "square", "squirrel", "stable", "stapler", "starling",
  "stream", "sturdy", "summit", "sunset", "swallow", "swan", "sweater", "tabby",
  "tangerine","teeth", "temple", "tender", "terrace", "thistle", "thunder", "timber", "toast",
  "token", "tomato", "topaz", "tortoise", "toucan", "trail", "trumpet", "tulip",
  "tundra", "tunnel", "turtle", "twig", "umbrella", "valley", "vanilla", "velvet",
  "vessel", "violet", "walnut", "walrus", "warble", "warden", "wasp", "wheat",
  "whisk", "willow", "window", "winter", "wonder", "wooden", "yonder", "zebra",
];
